version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo_admin_app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 1234:1234
